name: Setup
description: Setup node, etc

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Download node packages
      run: yarn install --immutable
      shell: bash
