name: Build website

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-site.yml'
      - 'website/**'

defaults:
  run:
    working-directory: website

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Test build website
        run: yarn build
